<?php
/*Clas autogenerated whith phpCriteria*/
class EntityHorarios {

	public $hrs_ID;
	public $FK_personal_pers_ID;
	public $hrs_horario;
	public $hrs_anio;
	public $audit_fecha;
	public $audit_usuario;
	public $audit_sistema;

	function __construct() {}
}
?>