<?php
/*Clas autogenerated whith phpCriteria*/
class EntityPersonal {

	public $pers_ID;
	public $FK_personas_per_ID;
	public $pers_tipo;
	public $pers_anio;
	public $audit_fecha;
	public $audit_usuario;
	public $audit_sistema;

	function __construct() {}
}
?>