<?php
/*Clas autogenerated whith phpCriteria*/
class EntityColegios {

	public $colegio_ID;
	public $nombre;
	public $FK_db_db_ID;
	public $direccion;
	public $telefono;
	public $rbd;
	public $col_director;
	public $col_comuna;
	public $col_url;
	public $col_decreto;
	public $col_anio;

	function __construct() {}
}
?>