<?php
/*Clas autogenerated whith phpCriteria*/
class EntityArancel {

	public $aran_ID;
	public $FK_colegios_colegio_ID;
	public $FK_curso;
	public $aran_monto;
	public $aran_anio;

	function __construct() {}
}
?>