<?php
/*Clas autogenerated whith phpCriteria*/
class EntityBecas {
    
	public $beca_ID;
	public $FK_rut;
	public $FK_colegios_colegio_ID;
	public $beca_anio;
	public $beca_porcentaje;
	public $beca_detalle;

	function __construct() {}
}
?>