<?php
/*Clas autogenerated whith phpCriteria*/
class EntityUsuarios {

	public $usr_ID;
	public $FK_colegios_colegio_ID;
	public $login;
	public $password;
	public $tipo;

	function __construct() {}
}
?>