<?php
/*Clas autogenerated whith phpCriteria*/
class EntityPersonas {

	public $per_ID;
	public $per_nombres;
	public $per_apellidop;
	public $per_apellidom;
	public $per_rut;
	public $per_fono;
	public $per_direccion;
	public $per_titulo;
	public $per_codigo_autorizacion;
	public $per_estado_titulo;

	function __construct() {}
}
?>